# Generated by Django 5.2.8 on 2025-11-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servicios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta", "Tarjeta de Crédito"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=50,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=100)),
                ("pagado", models.BooleanField(default=True)),
                (
                    "servicio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="servicios.servicio",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="Recibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.TextField()),
                ("observaciones", models.TextField(blank=True)),
                (
                    "pago",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibo",
                        to="facturas.pago",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
