# Generated by Django 5.2.8 on 2025-11-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sedes", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duracion_dias", models.IntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_contratacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_servicio", models.DateField()),
                ("costo_base", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "adicionales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("costo_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sedes.sede"
                    ),
                ),
                (
                    "tipo_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.tiposervicio",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_contratacion"],
            },
        ),
    ]
