# Generated by Django 5.2.8 on 2025-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=100)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                ("horario_atencion", models.CharField(default="24/7", max_length=100)),
                ("gerente", models.CharField(blank=True, max_length=100)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["ciudad", "nombre"],
            },
        ),
    ]
